### ISSUE TITLE
No module surgery

### ISSUE THREAD

**Issue by akshayborse** [YuvalNirkin/face_segmentation#10]
when I run 
```
python face_seg.py
```
I get an error as No module surgery

line number 4 in face_seg.py is
```
 import surgery
```
But there is no module as surgery any where on my system
from where can i get the surgery module

**Comment by YuvalNirkin** [comment]
I added the missing file.

Thank you.

**Comment by akshayborse** [comment]
Can you please tell me what is is the surgery library doing. Your code worked completely perfect when I commented "import surgery" and ran the code.

And after uncommenting that line and adding surgery.py to the folder it says surgery imported but unused, also code is working as perfect as it was working previously.
