### ISSUE TITLE
Asking for training dataset

### ISSUE THREAD

**Issue by AtenaKid** [YuvalNirkin/face_segmentation#11]
Hi 
Is it possible to have your training dataset?
I would like to train from scratch for a new model.

Best regards,

**Comment by YuvalNirkin** [comment]
Hi,
Please see #6.

Best,
Yuval

**Comment by ileniTudor** [comment]
> Hi
> Is it possible to have your training dataset?
> I would like to train from scratch for a new model.
> 
> Best regards,

Can take a look on this dataset:
http://www.cs.ubbcluj.ro/~dadi/face-hair-segm-database.html
