### ISSUE TITLE
how to crop face bbox

### ISSUE THREAD

**Issue by husencd** [YuvalNirkin/face_segmentation#12]
Hello. I want to use your model to segment my own face. But i have no idea about the pricinple of face bbox cropping. I failed to segment face when i used face bbox which is to tight. So i expand the face by some ratios. However, the result is not good enough as well.

Can u tell me how to choose the most suitable face to achieve your performance? Thank you.

**Comment by YuvalNirkin** [comment]
Hi, please see #8.
