### ISSUE TITLE
Network Output

### ISSUE THREAD

**Issue by mfournarakis** [YuvalNirkin/face_segmentation#15]
I'm trying to understand the output of the caffe network and where `argmax` prediction is coming from in the python interface: `out = net.blobs['score'].data[0].argmax(axis=0)`

The output: `net.blobs['score'].data` has 21 channels. What are the additional 20 channels and how do we know that if a face pixel is present, the maximum value will be in the second channel?

Thanks

**Comment by YuvalNirkin** [comment]
Exactly, the maximum value will be in the second channel for face pixels.

The other 19 channels are not used and were removed in the new model for the 300X300 resolution.
