### ISSUE TITLE
can you offer training file

### ISSUE THREAD

**Issue by sunjunlishi** [YuvalNirkin/face_segmentation#16]
How to organize data

**Comment by YuvalNirkin** [comment]
Hi,
Please see #6 about the the training dataset.
Otherwise if you want to use your own data, it has to follow the PASCAL VOC format.

Best,
Yuval

**Comment by sunjunlishi** [comment]
not training data。train_and_test.prototxt File

**Comment by sunjunlishi** [comment]
you only offered  test.prototxt file. and  your work is  cool.

**Comment by sunjunlishi** [comment]
such as loss layer？

**Comment by sunjunlishi** [comment]
Caffe training file？

**Comment by YuvalNirkin** [comment]
You can find the training files here:
https://github.com/shelhamer/fcn.berkeleyvision.org/tree/master/voc-fcn8s-atonce
