### ISSUE TITLE
CUDA CPU or GPU

### ISSUE THREAD

**Issue by miaoqiz** [YuvalNirkin/face_segmentation#20]
Hi,

Thanks for the software. When running "face_seg_image", here is an error:

-------------------------------------------------------------------------------------------------
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0212 19:18:55.035207 21461 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
-------------------------------------------------------------------------------------------------

Is there an option in the compiling stage to specify to use Caffe CPU?

Thanks!

**Comment by YuvalNirkin** [comment]
Yes, you can build Caffe with GPU support.
