### ISSUE TITLE
poor performance

### ISSUE THREAD

**Issue by bsdis** [YuvalNirkin/face_segmentation#23]
Hi, I tried your system - and maybe i am doing something wrong, but this system seems to give rather poor results. How were you able to get the results you describe?
I am using your implementation directly, so it should be same code i am running as you. 

See example of poor result here:

![](https://i.ibb.co/rttvRP2/Screenshot-2020-05-22-at-18-35-12.png)

Maybe you used some special model which you have not shared?

**Comment by YuvalNirkin** [comment]
Please see #8.

You can also try the new UNet model implemented in PyTorch [here](https://github.com/YuvalNirkin/fsgan).
