### ISSUE TITLE
Unable to segment eye-glasses

### ISSUE THREAD

**Issue by HoiM** [YuvalNirkin/face_segmentation#25]
Hello Yuval, 

Thank you for your project. I am also working on face swap projects. Now I am trying to tackle the problem of face occlusions. 

I find the performance on the README page really amazing. However, after installation I find that the performance on my face-swap training images not as good as your demo image. The model is unable to segment eye-glasses. 

Here are some examples:

![manmankan_big_qipu0_202393805_0 86573937186_5b56efa1b302c33404bda177](https://user-images.githubusercontent.com/32344416/111097603-d02d4a00-857c-11eb-8da0-736b86820e05.jpg)
![manmankan_big_qipu0_215746105_0 785859323308_5b56ee91ef924e6e48d046bc](https://user-images.githubusercontent.com/32344416/111097639-e1765680-857c-11eb-824b-5a0acfad9869.jpg)
![manmankan_big_qipu0_215790205_0 719922288978_5b56fcf9b302c3340590677d](https://user-images.githubusercontent.com/32344416/111097644-e3401a00-857c-11eb-95cc-ec49c8d06a5c.jpg)

I ran the model by this command:

```face_seg_image my_image.jpg -o . -m ../data/face_seg_fcn8s.caffemodel -d ../data/face_seg_fcn8s_deploy.prototxt```

where my_image.jpg is a 256x256 image in which the face is aligned via 5 landmarks (eyes, nose and mouth). 

Do you have any ideas on this? Or is there anything wrong with my input format?

Thank you in advance.

**Comment by YuvalNirkin** [comment]
The model was trained to remove the segmentation of only a limited number of sunglasses and so might fail sometimes. For glasses (with clear glass), the model was trained to include them as part of the face.
