### ISSUE TITLE
PyTorch implementation

### ISSUE THREAD

**Issue by andres-fr** [YuvalNirkin/face_segmentation#29]
Hi,

Thanks for the great work, many years later it is in fact still difficult to find this particular functionality and quality elsewhere.
Unfortunately, `Caffe` was never a tame dependency and this is not improving, to the point that it is harder to get it to work nicely with other dependencies as it is to rewrite full setups from scratch.

Fast forward to this moment, I've ported the model to PyTorch. Hopefully it can be helpful for others:
https://github.com/andres-fr/face_segmentation_pytorch

I'm happy to receive any feedback. Cheers!
Andres

**Comment by ohjarwa** [comment]
Thank you！ Very useful.

**Comment by YuvalNirkin** [comment]
Great work! Thank you!

**Comment by prokaryote-hgy** [comment]
Thank you! It helps a lot!
