### ISSUE TITLE
Segmentation fault (core dumped) when running the demo

### ISSUE THREAD

**Issue by hailehong** [YuvalNirkin/face_segmentation#4]
Hi,
I met this error when running the demo
I0921 13:13:41.511903  1711 net.cpp:242] This network produces output score
I0921 13:13:41.511961  1711 net.cpp:255] Network initialization done.
I0921 13:13:43.045377  1711 net.cpp:744] Ignoring source layer data
I0921 13:13:43.045660  1711 net.cpp:744] Ignoring source layer data_data_0_split
I0921 13:13:43.154325  1711 net.cpp:744] Ignoring source layer loss
**Segmentation fault (core dumped)**

I run in CPU mode, using a computer with 32 GB RAM. I think that is related to Caffe.
Did someone meet this error.
Thank you!

**Comment by Mayur28** [comment]
Hi @hailehong, 

I am experiencing the same issue, can you please let me know how you resolved the issue.

Thanks

**Comment by BenniKos** [comment]
@hailehong , @Mayur28 , @YuvalNirkin ,
I have the same problem when running the demo (python face_seg.py):
I0207 15:28:47.811776 23367 net.cpp:367] relu1_1 -> conv1_1 (in-place)
I0207 15:28:47.812227 23367 net.cpp:122] Setting up relu1_1
I0207 15:28:47.812237 23367 net.cpp:129] Top shape: 1 64 498 498 (15872256)
I0207 15:28:47.812242 23367 net.cpp:137] Memory required for data: 130218048
I0207 15:28:47.812245 23367 layer_factory.hpp:77] Creating layer conv1_2
I0207 15:28:47.812266 23367 net.cpp:84] Creating Layer conv1_2
I0207 15:28:47.812273 23367 net.cpp:406] conv1_2 <- conv1_1
I0207 15:28:47.812279 23367 net.cpp:380] conv1_2 -> conv1_2
Segmentation fault (core dumped)


When running via python in interfaces/python.
I use the caffe GPU Mode with a decent graphics card.

What went wrong, can anybody please help me ?
