### ISSUE TITLE
Compile error about protobuf versions.

### ISSUE THREAD

**Issue by lyycfairy** [YuvalNirkin/face_segmentation#5]
Hi, I got a error when I try to compile.

**/home/migudm/caffe/build/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers.  Please regenerate this file with a newer version of protoc.**

There are two versions of protobuf(2.5 and 3.5.1) in my Ubuntu14.  caffe is complied by protoc 2.5
I try to change the default protoc to version2.5. but it failed again.

shall I recomplie the Caffe with protoc 3.5.1 ? 
I have looked for many similar problems, but still not solved

**Comment by achalshah20** [comment]
How did you resolve this issue?
