### ISSUE TITLE
Could you release your database for face segmentation

### ISSUE THREAD

**Issue by goodluckcwl** [YuvalNirkin/face_segmentation#6]
I am interested in your work and want to train my own face segmentation network. Could you  release your database for face segmentation? Thanks a lot!

**Comment by YuvalNirkin** [comment]
Thank you for showing interest in our work.
Our dataset is based on NIST's IJB-A dataset and it's related JANUS CS2 dataset which was not made public just yet. We will release our dataset, providing this does not conflict with the licenses of the original images and videos.

**Comment by eladrich** [comment]
Hi Yuval,
Great work! Is there any update as to the release of the dataset / the fixed caffe model?

**Comment by YuvalNirkin** [comment]
The NIST's IJB-A dataset's videos part hasn't been released yet, consequently we still can't release our dataset.

The good news is that I am going to update this project soon, with a faster and better performing model, and maybe port it to more popular frameworks.

**Comment by Rettichhuang** [comment]
thx for ur explanation. i am looking forward to a python-version face-swap-master.because i am not familiar with C++ it is pretty difficult for me to understand the code<cry><cry><cry>

**Comment by ileniTudor** [comment]
For Face (and also hair segmentation) you can take a look on this dataset:
http://www.cs.ubbcluj.ro/~dadi/face-hair-segm-database.html
