### ISSUE TITLE
undefined reference to `gotoblas'

### ISSUE THREAD

**Issue by tjusxh** [YuvalNirkin/face_segmentation#7]
I come across the following question. Anyone can help me.
//usr/lib/libblas.so.3: undefined reference to `gotoblas'
collect2: error: ld returned 1 exit status
face_seg_image/CMakeFiles/face_seg_image.dir/build.make:151: recipe for target 'face_seg_image/face_seg_image' failed
make[2]: *** [face_seg_image/face_seg_image] Error 1
CMakeFiles/Makefile2:140: recipe for target 'face_seg_image/CMakeFiles/face_seg_image.dir/all' failed
make[1]: *** [face_seg_image/CMakeFiles/face_seg_image.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tjusxh** [comment]
The reason is the openblas and atlas conflict. I remove the openblas. It works.

**Comment by YuvalNirkin** [comment]
Great.
